name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'challenges'
        destination_repo: 'AdamLang96/DestDir'
        destination_folder: 'challenges'
        user_email: 'codesmith@codesmith.io'
        user_name: 'codesmith'

