name: Push files
on:
  push:
    branches:
      - 'main'
jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: AdamLang96/DestDir
          token: $ {{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          path: challenges
          
      - name: Copy Files
        shell: bash
        run: |
          cp -rf challenges/ challenges/
          
        
    
  
