name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - env:
       solutions_env: TRUE
       IMAGE_TAG: latest
      run: |
           docker build -f test.Dockerfile  -t test_tag:${IMAGE_TAG} .
           docker run -it test_tag:${IMAGE_TAG}
