name: pull-request
on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1

